steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/qolami-web-artifact/qolami-web-image:$COMMIT_SHA"
      - "."
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/qolami-web-artifact/qolami-web-image:$COMMIT_SHA"
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "qolami-web"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/qolami-web-artifact/qolami-web-image:$COMMIT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=1"
      - "--memory=2048Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=DATABASE_URL=database_url:latest,JWT_SECRET_KEY=jwt_secret_key:latest,EMAIL_USER=email_user:latest,EMAIL_PASS=email_pass:latest"
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/qolami-web-artifact/qolami-web-image:$COMMIT_SHA"
logsBucket: "gs://qolami-web-bucket/logs"
